### ISSUE TITLE
Question about combination with Preloader

### ISSUE THREAD

**Issue by tommyziegler** [thomasdarimont/spring-labs#2]
I forked your project and tried to add the JavaFx Preloader for a splash screen.
See the project: https://github.com/tommyziegler/spring-labs

When you run, you should be able to start the program with Preloader Class:
<code> $ mvn clean spring-boot:run -Djavafx.preloader=demo.AppInitializationPreloader </code>

My problem is that the splash screen while the startup of the spring context is hanging. Do you have an idea how to solve that problem?

Thx Tommy

**Comment by thomasdarimont** [comment]
Hi Tommy,

what do you mean with the Splash-Screen is hanging?

If I run the app with the `-Djavafx.preloader=demo.AppInitializationPreloader` setting from the IDE as well as on the console ... under OSX with Java 1.8u40 I briefly see the splash screen (with no animation) and then the main screen.

Whats missing?

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
I updated the springboot-javafx example to use the latest spring-boot 1.2.2 and added a streamlined version of your preloader example:
https://github.com/thomasdarimont/spring-labs/tree/master/spring-boot-javafx

Note that in order to have the preloader show up when executed via java -jar you have to add the preloader config before the jar argument like so:
`java -Djavafx.preloader=demo.AppPreloader -jar target/spring-boot-javafx-demo.jar`
or so:
`java -jar -Djavafx.preloader=demo.AppPreloader target/spring-boot-javafx-demo.jar`

this would NOT show the preloader: 
`java -jar target/spring-boot-javafx-demo.jar -Djavafx.preloader=demo.AppPreloader`

**Comment by tommyziegler** [comment]
Ok, thx for the information, yes right that can have some issue the order of the arguments.

But my main problem is that the preloaded, like you also say is not showing the animation. You can sometimes see it at the end really short.

When you use the same Scene with this ProgressIndicator in the App class you can see how its animated. I guess the Initialisation of SpringBoot is blocking that? Do you know any way how I can paralelize that!? My goal is that the Preloader Scene is visible, at the moment it looks that the GUI froze.  

Thx for your help

**Comment by tommyziegler** [comment]
Have you any idea!? Or do I have to look in direction of JavavFX Preloader's?

**Comment by tommyziegler** [comment]
Hello Thomas,

sorry for disturbing you, but you have no idea how to solve it?

Then I would maybe try to ask in th javaFX Community.

Thx for your cooperation Tommy

**Comment by thomasdarimont** [comment]
Hi Tommy,

no problem :) Unfortunately I haven't had time to experiment with this in the meantime :-/

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
Hi Tommy,

I eventually found a solution. The preloader animation is working now. I had to move the application context creation from the constructor into the `init` method of `AbstractJavaFxApplicationSupport`.

Feel free to give it a spin: https://github.com/thomasdarimont/spring-labs/tree/master/spring-boot-javafx

Btw. you can find a more advanced JavaFX integration (FXML binding support, View injection support, I18N) here: https://github.com/thomasdarimont/spring-labs/tree/master/spring-boot-javafx-jpa-demo

Cheers,
Thomas

**Comment by thomasdarimont** [comment]
Closing since this is solved now.

**Comment by tommyziegler** [comment]
Yes thx a lot again.
