### ISSUE TITLE
Investigate MessageSource based I18N mechanism for JavaFX integration.

### ISSUE THREAD

**Issue by thomasdarimont** [thomasdarimont/spring-labs#6]

**Comment by wimdeblauwe** [comment]
I managed to make this work using Spring Boot and JavaFX as follows:
1. Specify the location of the translations files in `application.properties`:
   spring.messages.basename=i18n/messages
2. Create a `messages.properties` file in `src/main/resources/i18n` folder
3. Additional languages also go in that folder. E.g. `messages_fr.properties` or `messages_cn.properties`
4. Make the FXMLLoader use the translations as follows:

```
        FXMLLoader loader = new FXMLLoader(getClass().getResource("main.fxml"));
        loader.setControllerFactory(context::getBean);
        loader.setResources(new MessageSourceResourceBundle(context.getBean(MessageSource.class),
                                                            Locale.getDefault()));
        rootNode = loader.load();
```

(Where `context` is the Spring ApplicationContext)

You can now access the translated text in a controller or a FXML view. For the controller, just inject an `MessageSource` instance and get the text:

```
messageSource.getMessage("machine.starting", null, Locale.getDefault())
```

For an FXML view, use the `%key` notation:

```
<Text fx:id="statusText" text="%machine.stopped"/>
```

I hope this helps you further.

**Comment by thomasdarimont** [comment]
Worked great thanks!
